export const pagesRoutes = [
  ["v-05cab828","/README%20copy.html",{"t":"Short Code Africa Docs","i":"home"},["/README copy.html","/README%20copy","/README copy.md","/README%20copy.md"]],
  ["v-8daa1a0e","/",{"t":"Introduction"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-1c7b2593","/guide/introduction.html",{"t":"Introduction"},["/guide/introduction","/guide/introduction.md"]],
  ["v-1473bf53","/demo/",{"t":"Features Demo","i":"discover"},["/demo/index.html","/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"t":"Disabling layout and features","i":"config"},["/demo/disable","/demo/disable.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"t":"Encryption Article","i":"lock"},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-438ffe52","/demo/markdown.html",{"t":"Markdown Enhance","i":"markdown"},["/demo/markdown","/demo/markdown.md"]],
  ["v-6e19edb7","/demo/page.html",{"t":"Page Config","i":"page"},["/demo/page","/demo/page.md"]],
  ["v-2bdf5602","/guide/actions/callingrest.html",{"t":"Calling a Restapi"},["/guide/actions/callingrest","/guide/actions/callingrest.md"]],
  ["v-64fbf580","/guide/actions/database.html",{"t":"Database Connection"},["/guide/actions/database","/guide/actions/database.md"]],
  ["v-0f87a7e4","/guide/actions/javascript.html",{"t":"Javascript Code"},["/guide/actions/javascript","/guide/actions/javascript.md"]],
  ["v-09131cfc","/guide/actions/sendingsms.html",{"t":"Sending Sms"},["/guide/actions/sendingsms","/guide/actions/sendingsms.md"]],
  ["v-e143fa62","/guide/howtos/retrieveactionresult.html",{"t":"Retrieve an action result in menu text"},["/guide/howtos/retrieveactionresult","/guide/howtos/retrieveactionresult.md"]],
  ["v-5662a8d1","/guide/howtos/retrievesessionvar.html",{"t":"Retrieve a session variable in menu text"},["/guide/howtos/retrievesessionvar","/guide/howtos/retrievesessionvar.md"]],
  ["v-fd4ff782","/guide/intro/getstarted.html",{"t":"Getting Started"},["/guide/intro/getstarted","/guide/intro/getstarted.md"]],
  ["v-085a3880","/guide/menus/addmenu.html",{"t":"Adding Menus"},["/guide/menus/addmenu","/guide/menus/addmenu.md"]],
  ["v-2e91c7ea","/guide/menus/menunaming.html",{"t":"Menu Naming"},["/guide/menus/menunaming","/guide/menus/menunaming.md"]],
  ["v-80cb4602","/guide/menus/menunavigation.html",{"t":"Menu Navigation base on input"},["/guide/menus/menunavigation","/guide/menus/menunavigation.md"]],
  ["v-f0a8da64","/guide/menus/retrievingmenuinput.html",{"t":"Retrieve Menu Input"},["/guide/menus/retrievingmenuinput","/guide/menus/retrievingmenuinput.md"]],
  ["v-3bab5db9","/guide/providers/",{"t":"ShortCode Providers"},["/guide/providers/index.html","/guide/providers/README.md"]],
  ["v-bb43e454","/guide/quickstart/emulator.html",{"t":"Running the Emulator"},["/guide/quickstart/emulator","/guide/quickstart/emulator.md"]],
  ["v-7f273cb3","/guide/quickstart/menus.html",{"t":"Adding menus"},["/guide/quickstart/menus","/guide/quickstart/menus.md"]],
  ["v-08096c92","/guide/quickstart/navigation.html",{"t":"Menu navigation"},["/guide/quickstart/navigation","/guide/quickstart/navigation.md"]],
  ["v-2948007a","/guide/quickstart/walkthroughfirstapp.html",{"t":"Walkthrough Building your first USSD app"},["/guide/quickstart/walkthroughfirstapp","/guide/quickstart/walkthroughfirstapp.md"]],
  ["v-3d54dcf2","/guide/deployment/connectionyourapp.html",{"t":"Connecting App to shortcode"},["/guide/deployment/connectionyourapp","/guide/deployment/connectionyourapp.md"]],
  ["v-9ebf8914","/guide/deployment/gettingshortcode.html",{"t":"Getting a ShortCode"},["/guide/deployment/gettingshortcode","/guide/deployment/gettingshortcode.md"]],
  ["v-551fd340","/guide/deployment/onpremisedeployment.html",{"t":"On Premise Deployment"},["/guide/deployment/onpremisedeployment","/guide/deployment/onpremisedeployment.md"]],
  ["v-c4fea9ce","/guide/recipes/checkregisteration.html",{"t":"Check if user is registered on first dial"},["/guide/recipes/checkregisteration","/guide/recipes/checkregisteration.md"]],
  ["v-94c30d6c","/guide/recipes/gotomenufromcode.html",{"t":"Branching to a different menu from code"},["/guide/recipes/gotomenufromcode","/guide/recipes/gotomenufromcode.md"]],
  ["v-178465d4","/guide/recipes/retrieveactionresult.html",{"t":"Retrieve an action result in code"},["/guide/recipes/retrieveactionresult","/guide/recipes/retrieveactionresult.md"]],
  ["v-57af41dc","/guide/recipes/setsessionvalue.html",{"t":"Set a session variable and retrieve it javascript"},["/guide/recipes/setsessionvalue","/guide/recipes/setsessionvalue.md"]],
  ["v-8b020f06","/guide/variables/actionresultref.html",{"t":"Action results in Menu"},["/guide/variables/actionresultref","/guide/variables/actionresultref.md"]],
  ["v-01061b80","/guide/variables/actions.html",{"t":"Action variables"},["/guide/variables/actions","/guide/variables/actions.md"]],
  ["v-5f042fd6","/guide/variables/menu.html",{"t":"Menu variables"},["/guide/variables/menu","/guide/variables/menu.md"]],
  ["v-48c6f987","/guide/variables/session.html",{"t":"Session Variables"},["/guide/variables/session","/guide/variables/session.md"]],
  ["v-47772e26","/guide/variables/variableref.html",{"t":"Variables in menu text"},["/guide/variables/variableref","/guide/variables/variableref.md"]],
  ["v-0bbdd52a","/guide/videos/",{"t":"Walthrough Videos"},["/guide/videos/index.html","/guide/videos/index.md"]],
  ["v-0b2d5f06","/guide/walkthroughs/etranzact.html",{"t":"Building eTranzact *389#"},["/guide/walkthroughs/etranzact","/guide/walkthroughs/etranzact.md"]],
  ["v-323158d4","/guide/walkthroughs/loanapp.html",{"t":"Building a sample loan app"},["/guide/walkthroughs/loanapp","/guide/walkthroughs/loanapp.md"]],
  ["v-e41cb516","/guide/walkthroughs/mpesa.html",{"t":"Building the MPESA app"},["/guide/walkthroughs/mpesa","/guide/walkthroughs/mpesa.md"]],
  ["v-1a28c885","/guide/walkthroughs/mpesaloan.html",{"t":"Building the MPESA app"},["/guide/walkthroughs/mpesaloan","/guide/walkthroughs/mpesaloan.md"]],
  ["v-ddca8c54","/guide/walkthroughs/mtnmobilemoney.html",{"t":"Building the MTN mobile money app"},["/guide/walkthroughs/mtnmobilemoney","/guide/walkthroughs/mtnmobilemoney.md"]],
  ["v-5285f9ee","/guide/walkthroughs/ussdbanking.html",{"t":"Sample USSD banking app"},["/guide/walkthroughs/ussdbanking","/guide/walkthroughs/ussdbanking.md"]],
  ["v-f44cf882","/guide/walkthroughs/zeepay.html",{"t":"Building Zeepay remittance app"},["/guide/walkthroughs/zeepay","/guide/walkthroughs/zeepay.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
